--- #YAML:1.0
name:               cpanupload
version:            1.1
abstract:           upload one or more files to CPAN, using PAUSE
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AppConfig::Std:       1.07
    File::Basename:       2.74
    HTTP::Request::Common:  1.28
    HTTP::Status:         1.28
    LWP::UserAgent:       2.036
    Net::FTP:             2.75
    Term::ReadKey:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
